runtime: nodejs18

service: default

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

network:
  forwarded_ports:
    - 65080
  instance_tag: websocket
